name: Build and archive extension


on:
  push:
    branches: [ main ]


jobs:

  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
      - run: node archiver.js

  commit:
    needs: archive
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated build archiver

