name: Build and release

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build devtools ($TARGET)
        run: npm run prod:$TARGET

      - name: archive build
        run: |
          zip -q -r -9 incoding.profiler.chrome.zip release/$TARGET

      - name: upload zip asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: $UPLOAD_URL
          asset_path: ./incoding.profiler.$TARGET.zip
          asset_name: incoding.profiler.$TARGET.zip
          asset_content_type: application/zip
