name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install zip
        run: sudo apt-get install zip

      - name: install dependencies
        run: npm ci

      - name: get version
        id: get_version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: ""
          bump_each_commit: false
          version_format: "${major}.${minor}.${increment}"

      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
        with:
          tag_name: ${{env.BRANCH}}/${{steps.get_version.outputs.version}}
          release_name: Release ${{env.BRANCH}}/${{steps.get_version.outputs.version}}
          draft: false
          prerelease: false

      - name: create chrome release
        uses: ./.github/workflows/build-release.yml
        env:
          TARGET: chrome
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}

      - name: create chrome release
        uses: ./.github/workflows/build-release.yml
        env:
          TARGET: edge
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
